version: "3"

networks:
  default:
    driver: bridge
  birdegop-net:
    external: true

services:
  
  outer-nginx:
    container_name: outer-nginx
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    build:
      context: .
      dockerfile: ./nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - seq
      - postgres_db
    networks:
      - default
      - birdegop-net
      
  
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./Lcb.Web/Dockerfile
    environment:
      TZ: "Europe/Moscow"
      ASPNETCORE_ConnectionStrings__MainDb: "Host=postgres_db;Port=5432;Username=postgres;Password=root;Database=Lcb;"
      ASPNETCORE_ENVIRONMENT: Development
      JwtConfig__Issuer: "localhost"
      JwtConfig__Audience: "localhost"
      JwtConfig__Key: "Al3x3yGaY!69420HanD$$0M3$$qU1DWarD"
      StaticConfig__StaticFilesPath: '/mounted/static'
    volumes:
      - /home/egop/lcb/statics:/mounted/static
    healthcheck:
      test: wget --no-verbose --tries=1 http://localhost/hc/check -qO- || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    ports:
      - "5000:80"
    depends_on:
      - postgres_db
      - seq
    networks:
      - default
      - birdegop-net
  
  postgres_db:
    container_name: PostgreSQL
    image: "postgres:latest"
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    restart: unless-stopped
    volumes:
      - /home/egop/lcb/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default
      - birdegop-net

  seq:
    image: datalust/seq
    restart: unless-stopped
    ports:
      - "50505:80"
    volumes:
      - /home/egop/lcb/seq:/data
    environment:
      ACCEPT_EULA: "Y"
      SEQ_API_CANONICALURI: "http://localhost:50505"
    networks:
      - default
      - birdegop-net