// <auto-generated />
using System;
using Lcb.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lcb.Infrastructure.Data.Migrations
{
    [DbContext(typeof(LcbContext))]
    [Migration("20230308002151_Updates")]
    partial class Updates
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Template.DAL.Models.Postcard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.Property<string>("WishFrom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WishText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WishTo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Postcards");
                });

            modelBuilder.Entity("Template.DAL.Models.PostcardImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("PostcardId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PostcardId");

                    b.ToTable("PostcardImage");
                });

            modelBuilder.Entity("Template.DAL.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Template.DAL.Models.Postcard", b =>
                {
                    b.HasOne("Template.DAL.Models.User", "User")
                        .WithMany("Postcards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Template.DAL.Models.PostcardImage", b =>
                {
                    b.HasOne("Template.DAL.Models.Postcard", "Postcard")
                        .WithMany("Images")
                        .HasForeignKey("PostcardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Postcard");
                });

            modelBuilder.Entity("Template.DAL.Models.Postcard", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Template.DAL.Models.User", b =>
                {
                    b.Navigation("Postcards");
                });
#pragma warning restore 612, 618
        }
    }
}
